const plantImages = {
  "amalaki": [ "1.jpg", "2.jpg", "3.jpg","4.jpg" ],
  "amra": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg" ],
  "apamarga": [ "1.jpg", "2.jpg", "3.jpg", ],
  "arjuna": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg" ],
  "arka": [ "1.jpg", "2.jpg", "3.jpg" ],
  "ashvatha": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg" ],
  "darbha": [ "1.jpg", "2.jpg", "3.jpg" ],
  "durva": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg" ],
  "jambu": [ "1.jpg", "2.jpg", "3.jpg" ],
  "kadamba": [ "1.jpg", "2.jpg", "3.jpg" ],
  "khadirah": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg" ],
  "kupilu": [ "1.jpg", "2.jpg", "3.jpg","4.jpg" ],
  "nagakesara": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg" ],
  "nimba": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"],
  "nyagrodha": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg" ],
  "palasa": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg" ],
  "panasa": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg" ],
  "rakthachandan": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
  "shami": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg" ],
  "sinshapa": [ "1.jpg", "2.jpg", "3.jpg" ],
  "udumbara": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg" ],
  "vamsha": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg"],
  "plaksha": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg"],
  "amrataka": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg" ],
  "bilva": [ "1.jpg", "2.jpg", "3.jpg", "4.jpg"],
}


export default plantImages;
